version: "3.8"

services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mysql
    hostname: mysql
    environment:
      - TZ=Asia/Tokyo
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    # - db-data:/var/lib/mysql
    networks:
      sample_coding_network:
        ipv4_address: 10.0.100.2

  localstack:
    build:
      context: ./localstack
      dockerfile: Dockerfile
    container_name: localstack
    hostname: localstack
    environment:
      - TZ=Asia/Tokyo
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DEFAULT_REGION=ap-northeast-1
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    volumes:
      - ./localstack/initaws.d:/docker-entrypoint-initaws.d
    networks:
      sample_coding_network:
        ipv4_address: 10.0.100.5

  api-mock:
    build:
      context: ./api-mock
      dockerfile: Dockerfile
    container_name: api-mock
    hostname: api-mock
    environment:
      - TZ=Asia/Tokyo
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_BUCKET_NAME=problem
    volumes:
      - ./api-mock:/work
    networks:
      sample_coding_network:
        ipv4_address: 10.0.100.3
    ports:
      - 8000:80
    working_dir: /work

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    hostname: php
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./php:/var/www/html
      - ./volume:/volume
    networks:
      sample_coding_network:
        ipv4_address: 10.0.100.4
    extra_hosts:
      - example.com:10.0.100.3
    depends_on:
      - mysql
      - api-mock
      - localstack

# volumes:
#  db-data:
#    driver: local

networks:
  sample_coding_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.100.0/24
